services:
 php:
   image: php:7.2-fpm
   volumes:
     - ./web:/www
     #- ./php.ini:/usr/local/etc/php/php.ini
 nginx:
   image: nginx:1.20.1
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params.modified
     - ./nginx/ssl:/etc/nginx/ssl
   volumes_from:
     - php
   ports:
     - 80:80
     #- 443:443
   links:
     - php
